//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Takes = new HashSet<Take>();
        }
    
        public int s_id { get; set; }
        public int rollno { get; set; }
        public string password { get; set; }
        public int t_id { get; set; }
    
        public virtual ICollection<Take> Takes { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
